package com.digitalrangersbd.DeepManage.Enum;

public enum Permission {

    //USER
    VIEW_USER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    //ROLE
    VIEW_ROLE,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,

    //PRODUCT
    VIEW_PRODUCT,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    //BRAND
    VIEW_BRAND,
    CREATE_BRAND,
    UPDATE_BRAND,
    DELETE_BRAND,

    //CATEGORY
    VIEW_CATEGORY,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,

    //PURCHASE
    VIEW_PURCHASE,
    CREATE_PURCHASE,
    UPDATE_PURCHASE,
    DELETE_PURCHASE,

    //SALE
    VIEW_SALE,
    CREATE_SALE,
    UPDATE_SALE,
    DELETE_SALE,

    //STOCK
    VIEW_STOCK,
    CREATE_STOCK,
    UPDATE_STOCK,
    DELETE_STOCK,

    //WAREHOUSE
    VIEW_WAREHOUSE,
    CREATE_WAREHOUSE,
    UPDATE_WAREHOUSE,
    DELETE_WAREHOUSE,

    //OUTLET
    VIEW_OUTLET,
    CREATE_OUTLET,
    UPDATE_OUTLET,
    DELETE_OUTLET,

    //EXPENSE
    VIEW_EXPENSE,
    CREATE_EXPENSE,
    UPDATE_EXPENSE,
    DELETE_EXPENSE,

    //EXPENSE_CATEGORY
    VIEW_EXPENSE_CATEGORY,
    CREATE_EXPENSE_CATEGORY,
    UPDATE_EXPENSE_CATEGORY,
    DELETE_EXPENSE_CATEGORY,


}
